// Code generated by niko-admin. DO NOT EDIT.
// Language switcher component
// Generate at: 2026-05-16

import {
  Button,
  Menu,
  MenuButton,
  MenuItem,
  MenuList,
  Icon,
  Text,
  Flex,
  useColorModeValue,
} from '@chakra-ui/react';
import { useTranslation } from 'react-i18next';
import { MdLanguage } from 'react-icons/md';
import { supportedLanguages, type LanguageCode } from '../../i18n';

export function LanguageSwitcher() {
  const { i18n } = useTranslation('common');
  const currentLang = i18n.language as LanguageCode;

  const bgHover = useColorModeValue('gray.100', 'whiteAlpha.200');
  const textColor = useColorModeValue('gray.700', 'white');
  const menuBg = useColorModeValue('white', 'navy.800');
  const menuBorder = useColorModeValue('gray.200', 'whiteAlpha.300');

  const handleLanguageChange = (langCode: LanguageCode) => {
    if (i18n.language === langCode) return;
    i18n.changeLanguage(langCode);
  };

  return (
    <Menu>
      <MenuButton
        as={Button}
        variant="ghost"
        size="sm"
        p="0px"
        minW="unset"
        w="40px"
        h="40px"
        borderRadius="50%"
        _hover={{ bg: bgHover }}
      >
        <Flex align="center" justify="center">
          <Icon as={MdLanguage} w="20px" h="20px" color={textColor} />
        </Flex>
      </MenuButton>
      <MenuList
        bg={menuBg}
        borderColor={menuBorder}
        borderWidth="1px"
        borderRadius="xl"
        boxShadow="xl"
        p="8px"
        minW="160px"
      >
        {supportedLanguages.map((lang) => (
          <MenuItem
            key={lang.code}
            onClick={() => handleLanguageChange(lang.code)}
            bg={lang.code === currentLang ? 'brand.50' : 'transparent'}
            color={lang.code === currentLang ? 'brand.600' : textColor}
            borderRadius="lg"
            mb="4px"
            _last={{ mb: '0px' }}
            _hover={{
              bg: lang.code === currentLang ? 'brand.100' : bgHover,
            }}
          >
            <Flex align="center" gap="10px">
              <Text fontSize="lg">{lang.flag}</Text>
              <Text fontSize="sm" fontWeight={lang.code === currentLang ? '600' : 'normal'}>
                {lang.name}
              </Text>
            </Flex>
          </MenuItem>
        ))}
      </MenuList>
    </Menu>
  );
}

export default LanguageSwitcher;
