// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/niko-admin/niko-admin/internal/config"
	"github.com/niko-admin/niko-admin/internal/pkg/ws"
	"github.com/niko-admin/niko-admin/internal/router"
)

// Injectors from wire.go:

// InitializeApp 使用 Wire 构建完整的应用依赖图。
func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	logger := provideLoggers(configConfig)
	db, err := provideDB(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := provideRedis(configConfig)
	if err != nil {
		return nil, err
	}
	manager := provideJWTManager(configConfig, client)
	hub := ws.NewHub()
	routerConfig := provideRouterConfig(configConfig)
	zapLogger := provideAccessLogger(logger)
	routerRouter := router.New(db, client, manager, hub, routerConfig, zapLogger)
	server := provideHTTPServer(routerRouter, configConfig)
	asynqServer := router.NewAsynqServer(client)
	serveMux := provideAsynqMux(db)
	app := &App{
		Loggers:     logger,
		HTTPServer:  server,
		AsynqServer: asynqServer,
		AsynqMux:    serveMux,
		Hub:         hub,
	}
	return app, nil
}
