// Code generated by niko-admin. DO NOT EDIT.
// i18n configuration constants
// Generate at: 2026-05-16

import type { I18nConfig, LanguageCode } from './types';

// i18next 配置常量
export const i18nConfig: I18nConfig = {
  fallbackLng: 'zh-CN',
  supportedLngs: ['zh-CN', 'zh-TW', 'en-US'],
  detection: {
    order: ['localStorage', 'navigator', 'htmlTag'],
    caches: ['localStorage'],
  },
  interpolation: {
    escapeValue: false, // React 会自动转义，不需要 i18next 再处理
  },
};

// localStorage key
export const LANGUAGE_STORAGE_KEY = 'niko-admin-language';

// 调试模式（开发环境启用）
export const DEBUG_I18N = false; // import.meta.env.DEV 会导致类型错误，暂时使用 false

// 命名空间配置
export const DEFAULT_NAMESPACE = 'common';

// 可用的命名空间
export const NAMESPACES = [
  'common',
  'layout',
  'auth',
  'menu',
  'permission',
  'modules/dashboard',
  'modules/users',
  'modules/roles',
  'modules/permissions',
  'modules/files',
  'modules/audit-logs',
  'modules/tasks',
] as const;

export type Namespace = typeof NAMESPACES[number];
