// Code generated by niko-admin. DO NOT EDIT.
// i18n initialization
// Generate at: 2026-05-16

import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

import { i18nConfig, DEBUG_I18N } from './config';
import zhCN from '../locales/zh-CN';
import zhTW from '../locales/zh-TW';
import enUS from '../locales/en-US';

// 资源对象
const resources = {
  'zh-CN': zhCN,
  'zh-TW': zhTW,
  'en-US': enUS,
};

// 导出资源类型
export type Resources = typeof resources;

// 初始化 i18next
i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    ...i18nConfig,
    debug: DEBUG_I18N,
    defaultNS: 'common',
    fallbackNS: 'common',
    react: {
      useSuspense: false,
    },
  });

// 重新导出类型
export type { LanguageCode } from './types';
export { supportedLanguages, defaultLanguage } from './types';

export default i18n;
