// Code generated by niko-admin. DO NOT EDIT.
// i18n types definition
// Generate at: 2026-05-16

import type { UseTranslationOptions } from 'react-i18next';

// 支持的语言代码
export type LanguageCode = 'zh-CN' | 'zh-TW' | 'en-US' | 'id-ID';

// 语言配置
export interface LanguageConfig {
  code: LanguageCode;
  name: string;
  flag: string;
  locale: string;
}

// 支持的语言列表
export const supportedLanguages: LanguageConfig[] = [
  {
    code: 'zh-CN',
    name: '简体中文',
    flag: '🇨🇳',
    locale: 'zh-CN',
  },
  {
    code: 'zh-TW',
    name: '繁體中文',
    flag: '🇹🇼',
    locale: 'zh-TW',
  },
  {
    code: 'en-US',
    name: 'English',
    flag: '🇺🇸',
    locale: 'en-US',
  },
  {
    code: 'id-ID',
    name: 'Bahasa Indonesia',
    flag: '🇮🇩',
    locale: 'id-ID',
  },
];

// 默认语言
export const defaultLanguage: LanguageCode = 'zh-CN';

// 语言映射表（用于浏览器语言检测）
export const browserLanguageMap: Record<string, LanguageCode> = {
  'zh': 'zh-CN',
  'zh-CN': 'zh-CN',
  'zh-Hans': 'zh-CN',
  'zh-TW': 'zh-TW',
  'zh-HK': 'zh-TW',
  'zh-Hant': 'zh-TW',
  'en': 'en-US',
  'en-US': 'en-US',
  'en-GB': 'en-US',
  'id': 'id-ID',
  'id-ID': 'id-ID',
};

// 获取浏览器对应的语言代码
export function getLanguageFromBrowser(browserLang: string): LanguageCode {
  return browserLanguageMap[browserLang] || defaultLanguage;
}

// i18next 配置选项
export interface I18nConfig {
  fallbackLng: LanguageCode;
  supportedLngs: LanguageCode[];
  detection: {
    order: string[];
    caches: string[];
  };
  interpolation: {
    escapeValue: boolean;
  };
}
