// Code generated by niko-admin. DO NOT EDIT.
// Date formatting hook using date-fns
// Generate at: 2026-05-16

import { useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import {
  format,
  formatDistance,
  formatRelative,
  Locale,
  isToday,
  isYesterday,
  differenceInMinutes,
  differenceInHours,
  differenceInDays,
} from 'date-fns';
import { zhCN, zhTW, enUS } from 'date-fns/locale';
import type { LanguageCode } from '../i18n';

// date-fns locale 映射
const localeMap: Record<LanguageCode, Locale> = {
  'zh-CN': zhCN,
  'zh-TW': zhTW,
  'en-US': enUS,
};

export function useDateFormat() {
  const { i18n, t } = useTranslation('common');
  const currentLocale = localeMap[i18n.language as LanguageCode] || zhCN;

  /**
   * 格式化日期
   * @param date - 日期对象或字符串
   * @param formatStr - 格式化字符串，默认 'yyyy年M月d日'
   */
  const formatDate = useCallback(
    (date: Date | string | number, formatStr?: string): string => {
      if (!date) return '';
      const d = typeof date === 'string' || typeof date === 'number' ? new Date(date) : date;
      const defaultFormat = t('date.format.date', { defaultValue: 'yyyy年M月d日' });
      return format(d, formatStr || defaultFormat, { locale: currentLocale });
    },
    [currentLocale, t]
  );

  /**
   * 格式化时间
   * @param date - 日期对象或字符串
   * @param formatStr - 格式化字符串，默认 'HH:mm'
   */
  const formatTime = useCallback(
    (date: Date | string | number, formatStr?: string): string => {
      if (!date) return '';
      const d = typeof date === 'string' || typeof date === 'number' ? new Date(date) : date;
      const defaultFormat = t('date.format.time', { defaultValue: 'HH:mm' });
      return format(d, formatStr || defaultFormat, { locale: currentLocale });
    },
    [currentLocale, t]
  );

  /**
   * 格式化日期时间
   * @param date - 日期对象或字符串
   * @param formatStr - 格式化字符串
   */
  const formatDateTime = useCallback(
    (date: Date | string | number, formatStr?: string): string => {
      if (!date) return '';
      const d = typeof date === 'string' || typeof date === 'number' ? new Date(date) : date;
      const defaultFormat = t('date.format.datetime', { defaultValue: 'yyyy年M月d日 HH:mm' });
      return format(d, formatStr || defaultFormat, { locale: currentLocale });
    },
    [currentLocale, t]
  );

  /**
   * 智能格式化（根据时间显示不同的格式）
   * - 今天：显示 "今天 HH:mm"
   * - 昨天：显示 "昨天 HH:mm"
   * - 其他：显示 "yyyy年M月d日"
   */
  const formatSmart = useCallback(
    (date: Date | string | number): string => {
      if (!date) return '';
      const d = typeof date === 'string' || typeof date === 'number' ? new Date(date) : date;

      if (isToday(d)) {
        return t('date.today') + ' ' + format(d, 'HH:mm', { locale: currentLocale });
      }
      if (isYesterday(d)) {
        return t('date.yesterday') + ' ' + format(d, 'HH:mm', { locale: currentLocale });
      }
      return formatDate(d);
    },
    [currentLocale, t, formatDate]
  );

  /**
   * 格式化相对时间（距离现在多久）
   * @param date - 日期对象或字符串
   * @param baseDate - 基准日期，默认当前时间
   */
  const formatRelative = useCallback(
    (date: Date | string | number, baseDate: Date = new Date()): string => {
      if (!date) return '';
      const d = typeof date === 'string' || typeof date === 'number' ? new Date(date) : date;

      const minutes = differenceInMinutes(baseDate, d);
      if (minutes < 1) return t('date.justNow');
      if (minutes < 60) return t('date.minutesAgo', { count: minutes });

      const hours = differenceInHours(baseDate, d);
      if (hours < 24) return t('date.hoursAgo', { count: hours });

      const days = differenceInDays(baseDate, d);
      if (days < 7) return t('date.daysAgo', { count: days });
      if (days < 30) return t('date.weeksAgo', { count: Math.floor(days / 7) });
      if (days < 365) return t('date.monthsAgo', { count: Math.floor(days / 30) });
      return t('date.yearsAgo', { count: Math.floor(days / 365) });
    },
    [currentLocale, t]
  );

  /**
   * 格式化距离（从现在开始多久之后）
   * @param date - 目标日期
   * @param baseDate - 基准日期，默认当前时间
   */
  const formatDistanceTo = useCallback(
    (date: Date | string | number, baseDate: Date = new Date()): string => {
      if (!date) return '';
      const d = typeof date === 'string' || typeof date === 'number' ? new Date(date) : date;

      const minutes = differenceInMinutes(d, baseDate);
      if (minutes < 1) return t('date.justNow');
      if (minutes < 60) return t('date.inMinutes', { count: minutes });

      const hours = differenceInHours(d, baseDate);
      if (hours < 24) return t('date.inHours', { count: hours });

      const days = differenceInDays(d, baseDate);
      if (days < 7) return t('date.inDays', { count: days });

      return formatDistance(d, baseDate, { addSuffix: true, locale: currentLocale });
    },
    [currentLocale, t]
  );

  return {
    formatDate,
    formatTime,
    formatDateTime,
    formatSmart,
    formatRelative,
    formatDistanceTo,
    currentLocale,
  };
}

export default useDateFormat;
