// Code generated by niko-admin. DO NOT EDIT.
// Dynamic route generator
// Generate at: 2026-05-16
/// <reference types="vite/client" />

import { Suspense, lazy, ComponentType } from 'react';
import { Route } from 'react-router-dom';
import { Icon } from '@chakra-ui/react';
import * as Icons from 'react-icons/md';
import { adminRoutes, authRoutes, allRoutes } from './routes.config';
import { RouteConfig, SidebarRouteType } from './types';
import type { Menu } from '../services/api';

// 菜单 code 到组件的映射
const menuComponentMap: Record<string, () => Promise<{ default: ComponentType<any> }>> = {
  'dashboard': () => import('../views/admin/default'),
  'users': () => import('../views/admin/users'),
  'roles': () => import('../views/admin/roles'),
  'permissions': () => import('../views/admin/permissions'),
  'files': () => import('../views/admin/files'),
  'audit-logs': () => import('../views/admin/audit-logs'),
  'tasks': () => import('../views/admin/tasks'),
  'brand-config': () => import('../views/admin/brand-config'),
  'mail-config': () => import('../views/admin/mail-config'),
  'feedback': () => import('../views/admin/feedback'),
};

const lazyCache = new Map<string, ComponentType<any>>();
let lazyCacheIdentity = '';

function updateLazyCacheIdentity(menus: Menu[]) {
  const next = menus.map((m) => `${m.id}:${m.code}:${m.path}`).sort().join('|');
  if (lazyCacheIdentity && lazyCacheIdentity !== next) {
    lazyCache.clear();
  }
  lazyCacheIdentity = next;
}

// 开发模式下清除缓存以支持 HMR
if (import.meta.hot) {
  import.meta.hot.dispose(() => {
    lazyCache.clear();
  });
}

function pruneLazyCache(activeKeys: string[]) {
  const activeSet = new Set(activeKeys);
  lazyCache.forEach((_, key) => {
    if (!activeSet.has(key)) lazyCache.delete(key);
  });
}

function createLazyComponent(
  key: string,
  importer: () => Promise<{ default: ComponentType<any> }>
): ComponentType<any> {
  const cached = lazyCache.get(key);
  if (cached) return cached;

  const LazyComponent = lazy(importer);
  const Wrapped = function (props: any) {
    return (
      <Suspense fallback={<div>Loading...</div>}>
        <LazyComponent {...props} />
      </Suspense>
    );
  };
  lazyCache.set(key, Wrapped);
  return Wrapped;
}

// 动态导入图标
export function getIconComponent(iconName: string): React.ReactNode {
  if (!iconName) return null;
  
  const IconComponent = Icons[iconName as keyof typeof Icons];
  if (!IconComponent) return null;

  return <Icon as={IconComponent} width="20px" height="20px" color="inherit" />;
}

export function generateRoutes(routes: RouteConfig[]): React.ReactNode[] {
  const activeKeys = routes.map((route) => `route:${route.id || route.path}`);
  pruneLazyCache(activeKeys);

  const result: React.ReactNode[] = [];
  for (let index = 0; index < routes.length; index++) {
    const route = routes[index];
    // 父菜单没有组件时，仅递归生成其子路由。
    if (!route.component) {
      if (route.children?.length) {
        result.push(...generateRoutes(route.children));
      }
      continue;
    }

    const cacheKey = `route:${route.id || route.path}`;
    const LazyComponent = createLazyComponent(cacheKey, route.component);
    result.push(
      <Route
        key={route.id || index}
        path={route.path}
        element={<LazyComponent />}
      />
    );
  }
  return result;
}

/**
 * 生成管理员路由组件
 */
export function generateAdminRoutes(): React.ReactNode[] {
  return generateRoutes(adminRoutes);
}

/**
 * 生成认证路由组件
 */
export function generateAuthRoutes(): React.ReactNode[] {
  return generateRoutes(authRoutes);
}

/**
 * 生成侧边栏路由（兼容旧版 Links.tsx）
 * @param t - 翻译函数
 */
export function generateSidebarRoutes(t: (key: string) => string): SidebarRouteType[] {
  const mapRoutes = (routes: RouteConfig[], depth = 0): SidebarRouteType[] => {
    const result: SidebarRouteType[] = [];
    for (const route of routes) {
      if (route.hidden) {
        // 隐藏父路由但不隐藏其子路由
        if (route.children && route.children.length > 0) {
          result.push(...mapRoutes(route.children, depth));
        }
        continue;
      }
      const fullPath = route.layout + route.path;
      const hasChildren = route.children && route.children.length > 0;
      result.push({
        key: route.id || fullPath,
        name: t(route.i18nKey),
        layout: route.layout,
        path: route.path,
        icon: getIconComponent(route.icon),
        secondary: route.secondary || false,
        items: depth < 1 && hasChildren ? mapRoutes(route.children!, depth + 1) : undefined,
      });
    }
    return result;
  };
  return mapRoutes(adminRoutes);
}

/**
 * 从用户菜单生成侧边栏路由
 * @param menus - 后端返回的用户菜单列表
 * @param t - i18n 翻译函数
 */
function normalizePath(p: string): string {
  return p.startsWith('/') ? p.slice(1) : p;
}

export function generateSidebarRoutesFromMenus(
  menus: Menu[],
  t: (key: string, options?: { defaultValue?: string }) => string,
): SidebarRouteType[] {
  const mapMenus = (menuList: Menu[], depth = 0): SidebarRouteType[] => {
    const result: SidebarRouteType[] = [];
    for (const menu of menuList) {
      if (menu.hidden) {
        if (menu.children && menu.children.length > 0) {
          result.push(...mapMenus(menu.children, depth));
        }
        continue;
      }
      result.push({
        // 兼容旧客户端或后端可能返回数字 ID 的情况，强制转换为 string
        key: String(menu.id || menu.code),
        name: t(`menu:${menu.code}`, { defaultValue: menu.name }),
        layout: '/admin',
        path: `/${normalizePath(menu.path)}`,
        icon: getIconComponent(menu.icon),
        secondary: false,
        items: depth < 1 && menu.children && menu.children.length > 0
          ? mapMenus(menu.children, depth + 1)
          : undefined,
      });
    }
    return result;
  };
  return mapMenus(menus);
}

/**
 * 从用户菜单生成 Route 组件
 * @param menus - 后端返回的用户菜单列表
 */
export function generateRoutesFromMenus(menus: Menu[]): React.ReactNode[] {
  updateLazyCacheIdentity(menus);
  const flattenMenus = (menuList: Menu[]): Menu[] => {
    const result: Menu[] = [];
    for (const menu of menuList) {
      result.push(menu);
      if (menu.children?.length) {
        result.push(...flattenMenus(menu.children));
      }
    }
    return result;
  };

  const allMenus = flattenMenus(menus);
  const routedMenus = allMenus.filter((menu) => menuComponentMap[menu.code]);
  pruneLazyCache(routedMenus.map((menu) => `menu:${menu.code}`));

  return routedMenus.map((menu) => {
    const LazyComponent = createLazyComponent(`menu:${menu.code}`, menuComponentMap[menu.code]);
    return (
      <Route
        key={menu.id}
        path={normalizePath(menu.path)}
        element={<LazyComponent />}
      />
    );
  });
}

/**
 * 获取激活的路由名称（从菜单）
 */
export function getActiveRouteFromMenus(
  menus: Menu[],
  pathname: string,
  t: (key: string, options?: { defaultValue?: string }) => string,
): string {
  const findName = (menuList: Menu[]): string | null => {
    for (const menu of menuList) {
      const path = `/${normalizePath(menu.path)}`;
      if (pathname === path || pathname.startsWith(path + '/')) {
        return t(`menu:${menu.code}`, { defaultValue: menu.name });
      }
      if (menu.children && menu.children.length > 0) {
        const childName = findName(menu.children);
        if (childName) return childName;
      }
    }
    return null;
  };
  return findName(menus) || t('menu:dashboard', { defaultValue: 'Dashboard' });
}

/**
 * 获取激活的路由名称（递归遍历嵌套子路由）
 */
export function getActiveRoute(
  routes: RouteConfig[],
  pathname: string,
  t: (key: string) => string
): string {
  const find = (items: RouteConfig[]): string | null => {
    for (const route of items) {
      const fullPath = route.layout + route.path;
      // 优先检查子路由以获得更高的匹配精确度
      if (route.children) {
        const child = find(route.children);
        if (child) return child;
      }
      if (pathname === fullPath || pathname.startsWith(fullPath + '/')) {
        return t(route.i18nKey);
      }
    }
    return null;
  };
  return find(routes) || t('layout.sidebar.dashboard');
}

/**
 * 获取激活的导航栏配置（递归遍历嵌套子路由）
 */
export function getActiveNavbar(routes: RouteConfig[], pathname: string): boolean {
  const find = (items: RouteConfig[]): boolean | null => {
    for (const route of items) {
      const fullPath = route.layout + route.path;
      // 优先检查子路由
      if (route.children) {
        const child = find(route.children);
        if (child !== null) return child;
      }
      if (pathname === fullPath || pathname.startsWith(fullPath + '/')) {
        return route.secondary || false;
      }
    }
    return null;
  };
  return find(routes) ?? false;
}

// 导出所有路由配置
export { adminRoutes, authRoutes, allRoutes };
export type { RouteConfig };
export default allRoutes;
