// Code generated by niko-admin. DO NOT EDIT.
// Dynamic route generator
// Generate at: 2026-05-16
/// <reference types="vite/client" />

import { Suspense, lazy, ComponentType } from 'react';
import { Route, RouteProps } from 'react-router-dom';
import { Icon } from '@chakra-ui/react';
import * as Icons from 'react-icons/md';
import { adminRoutes, authRoutes, allRoutes } from './routes.config';
import { RouteConfig } from './types';
import type { Menu } from '../services/api';

// 菜单 code 到组件的映射
const menuComponentMap: Record<string, () => Promise<{ default: ComponentType<any> }>> = {
  'dashboard': () => import('../views/admin/default'),
  'users': () => import('../views/admin/users'),
  'roles': () => import('../views/admin/roles'),
  'permissions': () => import('../views/admin/permissions'),
  'files': () => import('../views/admin/files'),
  'audit-logs': () => import('../views/admin/audit-logs'),
  'tasks': () => import('../views/admin/tasks'),
};

const lazyCache = new Map<string, ComponentType<any>>();
let lazyCacheIdentity = '';

function updateLazyCacheIdentity(menus: Menu[]) {
  const next = menus.map((m) => `${m.id}:${m.code}:${m.path}`).sort().join('|');
  if (lazyCacheIdentity && lazyCacheIdentity !== next) {
    lazyCache.clear();
  }
  lazyCacheIdentity = next;
}

// 开发模式下清除缓存以支持 HMR
if (import.meta.hot) {
  import.meta.hot.dispose(() => {
    lazyCache.clear();
  });
}

function pruneLazyCache(activeKeys: string[]) {
  const activeSet = new Set(activeKeys);
  for (const key of lazyCache.keys()) {
    if (!activeSet.has(key)) {
      lazyCache.delete(key);
    }
  }
}

function createLazyComponent(
  key: string,
  importer: () => Promise<{ default: ComponentType<any> }>
): ComponentType<any> {
  const cached = lazyCache.get(key);
  if (cached) return cached;

  const LazyComponent = lazy(importer);
  const Wrapped = function (props: any) {
    return (
      <Suspense fallback={<div>Loading...</div>}>
        <LazyComponent {...props} />
      </Suspense>
    );
  };
  lazyCache.set(key, Wrapped);
  return Wrapped;
}

// 动态导入图标
export function getIconComponent(iconName: string): React.ReactNode {
  if (!iconName) return null;
  
  const IconComponent = Icons[iconName as keyof typeof Icons];
  if (IconComponent) {
    return <Icon as={IconComponent} width="20px" height="20px" color="inherit" />;
  }
  return null;
}

/**
 * 根据路由配置生成 Route 组件
 */
export function generateRoutes(routes: RouteConfig[]): React.ReactNode[] {
  const activeKeys = routes.map((route) => `route:${route.id || route.path}`);
  pruneLazyCache(activeKeys);

  return routes.map((route, index) => {
    const cacheKey = `route:${route.id || route.path}`;
    const LazyComponent = createLazyComponent(cacheKey, route.component);
    return (
      <Route
        key={route.id || index}
        path={route.path}
        element={<LazyComponent />}
      />
    );
  });
}

/**
 * 生成管理员路由组件
 */
export function generateAdminRoutes(): React.ReactNode[] {
  return generateRoutes(adminRoutes);
}

/**
 * 生成认证路由组件
 */
export function generateAuthRoutes(): React.ReactNode[] {
  return generateRoutes(authRoutes);
}

/**
 * 生成侧边栏路由（兼容旧版 Links.tsx）
 * @param t - 翻译函数
 */
export function generateSidebarRoutes(t: (key: string) => string): RoutesType[] {
  return adminRoutes.map((route) => ({
    name: t(route.i18nKey),
    layout: route.layout,
    path: route.path,
    icon: getIconComponent(route.icon),
    secondary: route.secondary || false,
    component: null, // Sidebar 不需要 component
  }));
}

/**
 * 从用户菜单生成侧边栏路由
 * @param menus - 后端返回的用户菜单列表
 */
function normalizePath(p: string): string {
  return p.startsWith('/') ? p.slice(1) : p;
}

export function generateSidebarRoutesFromMenus(menus: Menu[]): RoutesType[] {
  const flattenMenus = (menuList: Menu[]): RoutesType[] => {
    const result: RoutesType[] = [];
    for (const menu of menuList) {
      result.push({
        name: menu.name,
        layout: '/admin',
        path: `/${normalizePath(menu.path)}`,
        icon: getIconComponent(menu.icon),
        secondary: false,
        component: null,
      });
      if (menu.children && menu.children.length > 0) {
        result.push(...flattenMenus(menu.children));
      }
    }
    return result;
  };
  return flattenMenus(menus);
}

/**
 * 从用户菜单生成 Route 组件
 * @param menus - 后端返回的用户菜单列表
 */
export function generateRoutesFromMenus(menus: Menu[]): React.ReactNode[] {
  updateLazyCacheIdentity(menus);
  const flattenMenus = (menuList: Menu[]): Menu[] => {
    const result: Menu[] = [];
    for (const menu of menuList) {
      result.push(menu);
      if (menu.children && menu.children.length > 0) {
        result.push(...flattenMenus(menu.children));
      }
    }
    return result;
  };

  const allMenus = flattenMenus(menus);
  const routedMenus = allMenus.filter((menu) => menuComponentMap[menu.code]);
  const activeKeys = routedMenus.map((menu) => `menu:${menu.code}`);
  pruneLazyCache(activeKeys);

  return routedMenus.map((menu) => {
    const cacheKey = `menu:${menu.code}`;
    const LazyComponent = createLazyComponent(cacheKey, menuComponentMap[menu.code]);
    return (
      <Route
        key={menu.id}
        path={normalizePath(menu.path)}
        element={<LazyComponent />}
      />
    );
  });
}

/**
 * 获取激活的路由名称（从菜单）
 */
export function getActiveRouteFromMenus(
  menus: Menu[],
  pathname: string,
): string {
  const findName = (menuList: Menu[]): string | null => {
    for (const menu of menuList) {
      const path = `/${normalizePath(menu.path)}`;
      if (pathname === path || pathname.startsWith(path + '/')) {
        return menu.name;
      }
      if (menu.children && menu.children.length > 0) {
        const childName = findName(menu.children);
        if (childName) return childName;
      }
    }
    return null;
  };
  return findName(menus) || 'Dashboard';
}

/**
 * 获取激活的路由名称
 */
export function getActiveRoute(
  routes: RouteConfig[],
  pathname: string,
  t: (key: string) => string
): string {
  for (const route of routes) {
    if (pathname.includes(route.path)) {
      return t(route.i18nKey);
    }
  }
  return t('layout.sidebar.dashboard');
}

/**
 * 获取激活的导航栏配置
 */
export function getActiveNavbar(routes: RouteConfig[], pathname: string): boolean {
  for (const route of routes) {
    if (pathname.includes(route.path)) {
      return route.secondary || false;
    }
  }
  return false;
}

// 导出所有路由配置
export { adminRoutes, authRoutes, allRoutes };
export type { RouteConfig };
export default allRoutes;
