// Code generated by niko-admin. DO NOT EDIT.
// Route configurations
// Generate at: 2026-05-16

import { RouteConfig } from './types';

/**
 * 管理后台路由配置
 * 注意：icon 使用 react-icons 的图标名称（如 'MdHome', 'MdPerson'）
 * 在 sidebar 中会动态映射到对应的图标组件
 */
export const adminRoutes: RouteConfig[] = [
  {
    id: 'dashboard',
    path: '/default',
    i18nKey: 'layout.sidebar.dashboard',
    icon: 'MdHome',
    component: () => import('../views/admin/default'),
    layout: '/admin',
  },
  {
    id: 'users',
    path: '/users',
    i18nKey: 'layout.sidebar.userManagement',
    icon: 'MdPerson',
    component: () => import('../views/admin/users'),
    layout: '/admin',
  },
  {
    id: 'roles',
    path: '/roles',
    i18nKey: 'layout.sidebar.roleManagement',
    icon: 'MdSecurity',
    component: () => import('../views/admin/roles'),
    layout: '/admin',
  },
  {
    id: 'permissions',
    path: '/permissions',
    i18nKey: 'layout.sidebar.permissionManagement',
    icon: 'MdVpnKey',
    component: () => import('../views/admin/permissions'),
    layout: '/admin',
  },
  {
    id: 'files',
    path: '/files',
    i18nKey: 'layout.sidebar.fileManagement',
    icon: 'MdFolder',
    component: () => import('../views/admin/files'),
    layout: '/admin',
  },
  {
    id: 'audit-logs',
    path: '/audit-logs',
    i18nKey: 'layout.sidebar.auditLogs',
    icon: 'MdHistory',
    component: () => import('../views/admin/audit-logs'),
    layout: '/admin',
  },
  {
    id: 'tasks',
    path: '/tasks',
    i18nKey: 'layout.sidebar.taskManagement',
    icon: 'MdAssignment',
    component: () => import('../views/admin/tasks'),
    layout: '/admin',
  },
];

/**
 * 认证页面路由配置
 */
export const authRoutes: RouteConfig[] = [
  {
    id: 'sign-in',
    path: '/sign-in',
    i18nKey: 'auth.login.title',
    icon: '',
    component: () => import('../views/auth/signIn'),
    layout: '/auth',
    hidden: true,
  },
];

/**
 * 所有路由配置
 */
export const allRoutes: RouteConfig[] = [...adminRoutes, ...authRoutes];

export default allRoutes;
