// Code generated by niko-admin. DO NOT EDIT.
// Route configuration types
// Generate at: 2026-05-16

import { ComponentType, ReactNode } from 'react';

// 路由配置接口（用于配置数据）
export interface RouteConfig {
  id: string;
  path: string;
  i18nKey: string; // 用于侧边栏菜单的翻译键
  icon: string; // 图标名称，用于动态导入
  component: () => Promise<{ default: ComponentType<any> }>;
  layout: '/admin' | '/auth' | '/rtl';
  secondary?: boolean;
  hidden?: boolean; // 是否在侧边栏隐藏
  children?: RouteConfig[];
}

// 侧边栏路由项（用于 Sidebar Links）
// 预期最大嵌套深度：2 层（父菜单 → 子菜单），UI 对更深层级不做保证
export interface SidebarRouteType {
  key: string;
  name: string;
  layout: string;
  path: string;
  icon?: ReactNode;
  secondary?: boolean;
  items?: SidebarRouteType[];
}
