// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package router

import (
	"github.com/google/wire"
	"github.com/niko-admin/niko-admin/internal/handler"
	"github.com/niko-admin/niko-admin/internal/middleware"
	"github.com/niko-admin/niko-admin/internal/pkg/jwt"
	"github.com/niko-admin/niko-admin/internal/pkg/ws"
	"github.com/niko-admin/niko-admin/internal/repository"
	"github.com/niko-admin/niko-admin/internal/service"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeRouteDeps 使用 Wire 构造路由注册所需依赖。
func InitializeRouteDeps(db *gorm.DB, rdb *redis.Client, jwtManager *jwt.Manager, hub *ws.Hub, cfg *Config) (*RouteDeps, error) {
	cache := providePermissionCache(rdb, cfg)
	auditRepository := repository.NewAuditRepository(db)
	auditService := service.NewAuditService(auditRepository)
	userRepository := repository.NewUserRepository(db)
	permissionRepository := repository.NewPermissionRepository(db)
	localStorage, err := provideAvatarStorage(cfg)
	if err != nil {
		return nil, err
	}
	authService := provideAuthService(userRepository, permissionRepository, rdb, jwtManager, localStorage)
	emailTokenRepository := repository.NewEmailTokenRepository(db)
	mailConfigRepository := repository.NewMailConfigRepository(db)
	inboundEmailRepository := repository.NewInboundEmailRepository(db)
	feedbackRepository := repository.NewFeedbackRepository(db)
	mailService := service.NewMailService(mailConfigRepository, inboundEmailRepository, feedbackRepository)
	emailVerificationService := service.NewEmailVerificationService(emailTokenRepository, userRepository, mailService)
	authHandler := handler.NewAuthHandlerWithEmail(authService, emailVerificationService, auditService)
	wsHandler := provideWSHandler(hub, jwtManager, cfg)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService, authService)
	roleRepository := repository.NewRoleRepository(db)
	roleService := service.NewRoleService(roleRepository, userRepository, rdb)
	roleHandler := handler.NewRoleHandler(roleService)
	permissionService := providePermissionService(permissionRepository, cache)
	permissionHandler := handler.NewPermissionHandler(permissionService)
	fileRepository := repository.NewFileRepository(db)
	fileOptions := provideFileOptions(cfg)
	fileService := provideFileService(fileRepository, fileOptions)
	fileHandler := handler.NewFileHandler(fileService)
	auditHandler := handler.NewAuditHandler(auditService)
	taskRepository := repository.NewTaskRepository(db)
	taskService := service.NewTaskService(taskRepository)
	taskHandler := handler.NewTaskHandler(taskService)
	brandConfigRepository := repository.NewBrandConfigRepository(db)
	brandService := provideBrandService(brandConfigRepository, localStorage)
	brandHandler := handler.NewBrandHandler(brandService)
	mailHandler := handler.NewMailHandler(mailService)
	feedbackService := service.NewFeedbackService(feedbackRepository, mailService)
	feedbackHandler := handler.NewFeedbackHandler(feedbackService)
	dashboardRepository := repository.NewDashboardRepository(db)
	dashboardService := service.NewDashboardService(dashboardRepository)
	dashboardHandler := handler.NewDashboardHandler(dashboardService)
	routeDeps := newRouteDeps(cache, auditService, authHandler, wsHandler, userHandler, roleHandler, permissionHandler, fileHandler, auditHandler, taskHandler, brandHandler, mailHandler, feedbackHandler, dashboardHandler)
	return routeDeps, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewUserRepository, repository.NewRoleRepository, repository.NewPermissionRepository, repository.NewAuditRepository, repository.NewFileRepository, repository.NewTaskRepository, repository.NewDashboardRepository, repository.NewBrandConfigRepository, repository.NewMailConfigRepository, repository.NewEmailTokenRepository, repository.NewInboundEmailRepository, repository.NewFeedbackRepository)

var serviceSet = wire.NewSet(
	provideAvatarStorage,
	providePermissionCache,
	provideFileOptions,
	provideFileService,
	provideAuthService,
	provideBrandService,
	providePermissionService, service.NewAuditService, wire.Bind(new(middleware.AuditLogger), new(*service.AuditService)), service.NewUserService, service.NewRoleService, service.NewTaskService, service.NewDashboardService, service.NewMailService, service.NewEmailVerificationService, service.NewFeedbackService,
)

var handlerSet = wire.NewSet(handler.NewAuthHandlerWithEmail, provideWSHandler, handler.NewUserHandler, handler.NewRoleHandler, handler.NewPermissionHandler, handler.NewFileHandler, handler.NewAuditHandler, handler.NewTaskHandler, handler.NewBrandHandler, handler.NewMailHandler, handler.NewFeedbackHandler, handler.NewDashboardHandler)
