// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/file.go
// Generate at: 2026-05-15 22:05:18

package repository

import (
	"gorm.io/gorm"

	"github.com/niko-admin/niko-admin/internal/model"
)

// FileRepository handles database operations for File model.
type FileRepository struct {
	db *gorm.DB
}

// NewFileRepository creates a new FileRepository.
func NewFileRepository(db *gorm.DB) *FileRepository {
	return &FileRepository{db: db}
}

// FindByID finds a file by its ID.
func (r *FileRepository) FindByID(id string) (*model.File, error) {
	var item model.File
	err := r.db.Where("id = ?", id).First(&item).Error
	return &item, err
}

// Create inserts a new file record.
func (r *FileRepository) Create(item *model.File) error {
	return r.db.Create(item).Error
}

// Update saves changes to a file record.
func (r *FileRepository) Update(item *model.File) error {
	return r.db.Save(item).Error
}

// Delete removes a file by its ID.
func (r *FileRepository) Delete(id string) error {
	return r.db.Where("id = ?", id).Delete(&model.File{}).Error
}

// List returns a paginated list of files.
func (r *FileRepository) List(page, pageSize int) ([]model.File, int64, error) {
	var items []model.File
	var total int64

	query := r.db.Model(&model.File{})
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	offset := (page - 1) * pageSize
	err := query.Offset(offset).Limit(pageSize).Order("created_at DESC").Find(&items).Error
	return items, total, err
}
