// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/file.go
// Generate at: 2026-05-15 22:05:18

// Package repository 提供数据访问层实现，封装 GORM 数据库操作。
package repository

import (
	"context"
	"time"

	"gorm.io/gorm"

	"github.com/niko-admin/niko-admin/internal/dto"
	"github.com/niko-admin/niko-admin/internal/model"
	"github.com/niko-admin/niko-admin/internal/pkg/scopes"
)

// FileRepository 处理 File 和 FileChunk 模型的数据库读写操作
type FileRepository struct {
	db *gorm.DB // GORM 数据库连接实例
}

// NewFileRepository 创建并返回一个新的 FileRepository 实例
func NewFileRepository(db *gorm.DB) *FileRepository {
	return &FileRepository{db: db}
}

// FindByID 根据主键 ID 查询单个已上传文件元数据
func (r *FileRepository) FindByID(ctx context.Context, id string) (*model.File, error) {
	var item model.File
	err := r.db.WithContext(ctx).Where("id = ?", id).First(&item).Error
	return &item, err
}

// Create 插入一条新的已上传文件记录
func (r *FileRepository) Create(ctx context.Context, item *model.File) error {
	return r.db.WithContext(ctx).Create(item).Error
}

// Update 更新已存在文件的记录信息
func (r *FileRepository) Update(ctx context.Context, item *model.File) error {
	return r.db.WithContext(ctx).Save(item).Error
}

// Delete 根据 ID 物理/软删除文件记录
func (r *FileRepository) Delete(ctx context.Context, id string) error {
	return r.db.WithContext(ctx).Where("id = ?", id).Delete(&model.File{}).Error
}

// FindByMD5 根据文件 MD5 查询已上传文件元数据。
func (r *FileRepository) FindByMD5(ctx context.Context, md5Hash string) (*model.File, error) {
	var item model.File
	err := r.db.WithContext(ctx).Where("md5 = ?", md5Hash).First(&item).Error
	return &item, err
}

// List 分页查询并返回满足筛选条件的文件列表及总数
func (r *FileRepository) List(ctx context.Context, req dto.FileListRequest) ([]model.File, int64, error) {
	var items []model.File
	var total int64

	query := r.db.WithContext(ctx).Model(&model.File{}).Scopes(req.FilterScopes()...)
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	err := query.Scopes(
		scopes.Paginate(req.GetPage(), req.GetPageSize()),
		scopes.OrderBy(req.Sort, req.Order, model.File{}.SortableFields()...),
	).Find(&items).Error
	return items, total, err
}

// FindByUploadID 根据 upload_id 查询分块上传任务信息
func (r *FileRepository) FindByUploadID(ctx context.Context, uploadID string) (*model.FileChunk, error) {
	var chunk model.FileChunk
	err := r.db.WithContext(ctx).Where("upload_id = ?", uploadID).First(&chunk).Error
	return &chunk, err
}

// CreateChunk 创建一条新的分块上传任务记录
func (r *FileRepository) CreateChunk(ctx context.Context, chunk *model.FileChunk) error {
	return r.db.WithContext(ctx).Create(chunk).Error
}

// FindByUploadIDWithStatus 根据 upload_id 及特定状态查询分块上传任务信息
func (r *FileRepository) FindByUploadIDWithStatus(ctx context.Context, uploadID, status string) (*model.FileChunk, error) {
	var chunk model.FileChunk
	err := r.db.WithContext(ctx).Where("upload_id = ? AND status = ?", uploadID, status).First(&chunk).Error
	return &chunk, err
}

// UpdateChunkUploadedChunks 更新已上传分块索引的 JSON 记录
func (r *FileRepository) UpdateChunkUploadedChunks(ctx context.Context, uploadID, uploadedChunksJSON string) error {
	return r.db.WithContext(ctx).Model(&model.FileChunk{}).Where("upload_id = ?", uploadID).Update("uploaded_chunks", uploadedChunksJSON).Error
}

// UpdateChunkStatus 更新分块上传任务的状态
func (r *FileRepository) UpdateChunkStatus(ctx context.Context, uploadID, status string) error {
	return r.db.WithContext(ctx).Model(&model.FileChunk{}).Where("upload_id = ?", uploadID).Update("status", status).Error
}

// UpdateChunkCompleted 标记分块上传任务已完成合并，并写入完成时间
func (r *FileRepository) UpdateChunkCompleted(ctx context.Context, uploadID string, completedAt *time.Time) error {
	return r.db.WithContext(ctx).Model(&model.FileChunk{}).Where("upload_id = ?", uploadID).Updates(map[string]interface{}{
		"status":       "completed",
		"completed_at": completedAt,
	}).Error
}

// DeleteChunkByUploadID 根据 upload_id 删除一条分块任务记录
func (r *FileRepository) DeleteChunkByUploadID(ctx context.Context, uploadID string) error {
	return r.db.WithContext(ctx).Where("upload_id = ?", uploadID).Delete(&model.FileChunk{}).Error
}
