// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/permission.go
// Generate at: 2026-05-15 22:05:18

package repository

import (
	"gorm.io/gorm"

	"github.com/niko-admin/niko-admin/internal/model"
)

// PermissionRepository handles database operations for Permission model.
type PermissionRepository struct {
	db *gorm.DB
}

// NewPermissionRepository creates a new PermissionRepository.
func NewPermissionRepository(db *gorm.DB) *PermissionRepository {
	return &PermissionRepository{db: db}
}

// FindByID finds a permission by its ID.
func (r *PermissionRepository) FindByID(id string) (*model.Permission, error) {
	var item model.Permission
	err := r.db.Where("id = ?", id).First(&item).Error
	return &item, err
}

// Create inserts a new permission record.
func (r *PermissionRepository) Create(item *model.Permission) error {
	return r.db.Create(item).Error
}

// Update saves changes to a permission record.
func (r *PermissionRepository) Update(item *model.Permission) error {
	return r.db.Save(item).Error
}

// Delete removes a permission by its ID.
func (r *PermissionRepository) Delete(id string) error {
	return r.db.Where("id = ?", id).Delete(&model.Permission{}).Error
}

// List returns a paginated list of permissions.
func (r *PermissionRepository) List(page, pageSize int) ([]model.Permission, int64, error) {
	var items []model.Permission
	var total int64

	query := r.db.Model(&model.Permission{})
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	offset := (page - 1) * pageSize
	err := query.Offset(offset).Limit(pageSize).Order("created_at DESC").Find(&items).Error
	return items, total, err
}
