// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/role.go
// Generate at: 2026-05-15 22:05:18

package repository

import (
	"gorm.io/gorm"

	"github.com/niko-admin/niko-admin/internal/model"
)

// RoleRepository handles database operations for Role model.
type RoleRepository struct {
	db *gorm.DB
}

// NewRoleRepository creates a new RoleRepository.
func NewRoleRepository(db *gorm.DB) *RoleRepository {
	return &RoleRepository{db: db}
}

// FindByID finds a role by its ID.
func (r *RoleRepository) FindByID(id string) (*model.Role, error) {
	var item model.Role
	err := r.db.Where("id = ?", id).First(&item).Error
	return &item, err
}

// Create inserts a new role record.
func (r *RoleRepository) Create(item *model.Role) error {
	return r.db.Create(item).Error
}

// Update saves changes to a role record.
func (r *RoleRepository) Update(item *model.Role) error {
	return r.db.Save(item).Error
}

// Delete removes a role by its ID.
func (r *RoleRepository) Delete(id string) error {
	return r.db.Where("id = ?", id).Delete(&model.Role{}).Error
}

// List returns a paginated list of roles.
func (r *RoleRepository) List(page, pageSize int) ([]model.Role, int64, error) {
	var items []model.Role
	var total int64

	query := r.db.Model(&model.Role{})
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	offset := (page - 1) * pageSize
	err := query.Offset(offset).Limit(pageSize).Order("created_at DESC").Find(&items).Error
	return items, total, err
}
