// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/role.go
// Generate at: 2026-05-15 22:05:18

// Package repository 提供数据访问层实现，封装 GORM 数据库操作。
package repository

import (
	"context"

	"gorm.io/gorm"

	"github.com/niko-admin/niko-admin/internal/dto"
	"github.com/niko-admin/niko-admin/internal/model"
	"github.com/niko-admin/niko-admin/internal/pkg/scopes"
)

// RoleRepository 处理 Role 角色模型的数据持久化操作
type RoleRepository struct {
	db *gorm.DB // GORM 数据库连接实例
}

// NewRoleRepository 创建并返回一个新的 RoleRepository 实例
func NewRoleRepository(db *gorm.DB) *RoleRepository {
	return &RoleRepository{db: db}
}

// FindByID 根据主键 ID 查询单个角色信息 (并预加载角色关联的所有权限)
func (r *RoleRepository) FindByID(ctx context.Context, id string) (*model.Role, error) {
	var item model.Role
	err := r.db.WithContext(ctx).Preload("Permissions").Where("id = ?", id).First(&item).Error
	return &item, err
}

// Create 插入一条新的角色记录
func (r *RoleRepository) Create(ctx context.Context, item *model.Role) error {
	return r.db.WithContext(ctx).Create(item).Error
}

// Update 更新已存在的角色字段 (排除权限多对多关联的直接更新，走 Updates map)
func (r *RoleRepository) Update(ctx context.Context, item *model.Role) error {
	updates := map[string]any{
		"name":        item.Name,
		"description": item.Description,
		"sort_order":  item.SortOrder,
		"status":      item.Status,
		"level":       item.Level,
		"updated_by":  item.UpdatedBy,
	}
	return r.db.WithContext(ctx).Model(&model.Role{}).Where("id = ?", item.ID).Updates(updates).Error
}

// Delete 删除指定角色记录，同时在事务中级联清理角色权限表与用户角色表关系
func (r *RoleRepository) Delete(ctx context.Context, id string) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		// 1. 删除关联的角色权限多对多表数据
		if err := tx.Where("role_id = ?", id).Delete(&model.RolePermission{}).Error; err != nil {
			return err
		}
		// 2. 删除用户与该角色的多对多关系表数据
		if err := tx.Where("role_id = ?", id).Delete(&model.UserRole{}).Error; err != nil {
			return err
		}
		// 3. 删除角色主表记录
		if err := tx.Where("id = ?", id).Delete(&model.Role{}).Error; err != nil {
			return err
		}
		return nil
	})
}

// List 分页查询并返回满足过滤条件的角色的列表
func (r *RoleRepository) List(ctx context.Context, req dto.RoleListRequest) ([]model.Role, int64, error) {
	var items []model.Role
	var total int64

	query := r.db.WithContext(ctx).Model(&model.Role{}).Scopes(req.FilterScopes()...)
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	err := query.Scopes(
		scopes.Paginate(req.GetPage(), req.GetPageSize()),
		scopes.OrderBy(req.Sort, req.Order, model.Role{}.SortableFields()...),
	).Preload("Permissions").Find(&items).Error
	return items, total, err
}

// ListForExport 返回符合筛选条件的角色列表，用于导出。
func (r *RoleRepository) ListForExport(ctx context.Context, req dto.RoleListRequest, limit int) ([]model.Role, error) {
	var items []model.Role
	err := r.db.WithContext(ctx).
		Model(&model.Role{}).
		Scopes(req.FilterScopes()...).
		Scopes(scopes.OrderBy(req.Sort, req.Order, model.Role{}.SortableFields()...), scopes.OrderByDefault()).
		Limit(limit).
		Preload("Permissions").
		Find(&items).Error
	return items, err
}

// FindByName 根据角色名称查询角色信息
func (r *RoleRepository) FindByName(ctx context.Context, name string) (*model.Role, error) {
	var role model.Role
	err := r.db.WithContext(ctx).Where("name = ?", name).First(&role).Error
	return &role, err
}

// CountByName 统计使用指定名称的角色数，可选排查排除指定的角色 ID (用于唯一性验证)
func (r *RoleRepository) CountByName(ctx context.Context, name string, excludeID string) (int64, error) {
	var count int64
	query := r.db.WithContext(ctx).Model(&model.Role{}).Where("name = ?", name)
	if excludeID != "" {
		query = query.Where("id != ?", excludeID)
	}
	err := query.Count(&count).Error
	return count, err
}

// CountAssignedUsers 统计有多少个用户被授予了指定的角色 (用以做级联防删判断)
func (r *RoleRepository) CountAssignedUsers(ctx context.Context, roleID string) (int64, error) {
	var count int64
	err := r.db.WithContext(ctx).Table("user_roles").Where("role_id = ?", roleID).Count(&count).Error
	return count, err
}

// GetPermissionsByRoleID 根据角色 ID 关联角色权限表，查询该角色关联的所有权限记录
func (r *RoleRepository) GetPermissionsByRoleID(ctx context.Context, roleID string) ([]model.Permission, error) {
	var permissions []model.Permission
	err := r.db.WithContext(ctx).
		Joins("JOIN role_permissions ON role_permissions.permission_id = permissions.id").
		Where("role_permissions.role_id = ?", roleID).
		Order("permissions.sort_order ASC, permissions.created_at ASC").
		Find(&permissions).Error
	return permissions, err
}

// ReplacePermissions 在事务中先清理原有的角色权限多对多关联，再重新插入新的权限列表以实现全新分配操作
func (r *RoleRepository) ReplacePermissions(ctx context.Context, roleID string, permissionIDs []string) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		// 1. 删除旧关联关系
		if err := tx.Where("role_id = ?", roleID).Delete(&model.RolePermission{}).Error; err != nil {
			return err
		}
		// 2. 插入新关联关系
		if len(permissionIDs) > 0 {
			rolePerms := make([]model.RolePermission, 0, len(permissionIDs))
			for _, pid := range permissionIDs {
				rolePerms = append(rolePerms, model.RolePermission{
					RoleID:       roleID,
					PermissionID: pid,
				})
			}
			return tx.Create(&rolePerms).Error
		}
		return nil
	})
}
