// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/role.go
// Generate at: 2026-05-15 22:05:18

package repository

import (
	"context"

	"gorm.io/gorm"

	"github.com/niko-admin/niko-admin/internal/dto"
	"github.com/niko-admin/niko-admin/internal/model"
	"github.com/niko-admin/niko-admin/internal/pkg/scopes"
)

// RoleRepository handles database operations for Role model.
type RoleRepository struct {
	db *gorm.DB
}

// NewRoleRepository creates a new RoleRepository.
func NewRoleRepository(db *gorm.DB) *RoleRepository {
	return &RoleRepository{db: db}
}

// FindByID finds a role by its ID.
func (r *RoleRepository) FindByID(ctx context.Context, id string) (*model.Role, error) {
	var item model.Role
	err := r.db.WithContext(ctx).Preload("Permissions").Where("id = ?", id).First(&item).Error
	return &item, err
}

// Create inserts a new role record.
func (r *RoleRepository) Create(ctx context.Context, item *model.Role) error {
	return r.db.WithContext(ctx).Create(item).Error
}

// Update saves mutable role fields.
func (r *RoleRepository) Update(ctx context.Context, item *model.Role) error {
	updates := map[string]any{
		"name":        item.Name,
		"description": item.Description,
		"sort_order":  item.SortOrder,
		"status":      item.Status,
		"level":       item.Level,
		"updated_by":  item.UpdatedBy,
	}
	return r.db.WithContext(ctx).Model(&model.Role{}).Where("id = ?", item.ID).Updates(updates).Error
}

// Delete removes a role by its ID and cleans up join tables.
func (r *RoleRepository) Delete(ctx context.Context, id string) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Where("role_id = ?", id).Delete(&model.RolePermission{}).Error; err != nil {
			return err
		}
		if err := tx.Where("role_id = ?", id).Delete(&model.UserRole{}).Error; err != nil {
			return err
		}
		if err := tx.Where("id = ?", id).Delete(&model.Role{}).Error; err != nil {
			return err
		}
		return nil
	})
}

// List returns a paginated list of roles with optional filters.
func (r *RoleRepository) List(ctx context.Context, req dto.RoleListRequest) ([]model.Role, int64, error) {
	var items []model.Role
	var total int64

	query := r.db.WithContext(ctx).Model(&model.Role{}).Scopes(req.FilterScopes()...)
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	err := query.Scopes(
		scopes.Paginate(req.GetPage(), req.GetPageSize()),
		scopes.OrderBy(req.Sort, req.Order, model.Role{}.SortableFields()...),
	).Preload("Permissions").Find(&items).Error
	return items, total, err
}

// FindByName finds a role by name.
func (r *RoleRepository) FindByName(ctx context.Context, name string) (*model.Role, error) {
	var role model.Role
	err := r.db.WithContext(ctx).Where("name = ?", name).First(&role).Error
	return &role, err
}

// CountByName counts roles with the given name, optionally excluding an ID.
func (r *RoleRepository) CountByName(ctx context.Context, name string, excludeID string) (int64, error) {
	var count int64
	query := r.db.WithContext(ctx).Model(&model.Role{}).Where("name = ?", name)
	if excludeID != "" {
		query = query.Where("id != ?", excludeID)
	}
	err := query.Count(&count).Error
	return count, err
}

// CountAssignedUsers returns how many users are assigned to the given role.
func (r *RoleRepository) CountAssignedUsers(ctx context.Context, roleID string) (int64, error) {
	var count int64
	err := r.db.WithContext(ctx).Table("user_roles").Where("role_id = ?", roleID).Count(&count).Error
	return count, err
}

// GetPermissionsByRoleID returns permissions assigned to a role via the join table.
func (r *RoleRepository) GetPermissionsByRoleID(ctx context.Context, roleID string) ([]model.Permission, error) {
	var permissions []model.Permission
	err := r.db.WithContext(ctx).
		Joins("JOIN role_permissions ON role_permissions.permission_id = permissions.id").
		Where("role_permissions.role_id = ?", roleID).
		Order("permissions.sort_order ASC, permissions.created_at ASC").
		Find(&permissions).Error
	return permissions, err
}

// ReplacePermissions replaces all permission associations for a role in a transaction.
func (r *RoleRepository) ReplacePermissions(ctx context.Context, roleID string, permissionIDs []string) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Where("role_id = ?", roleID).Delete(&model.RolePermission{}).Error; err != nil {
			return err
		}
		if len(permissionIDs) > 0 {
			rolePerms := make([]model.RolePermission, 0, len(permissionIDs))
			for _, pid := range permissionIDs {
				rolePerms = append(rolePerms, model.RolePermission{
					RoleID:       roleID,
					PermissionID: pid,
				})
			}
			return tx.Create(&rolePerms).Error
		}
		return nil
	})
}
