// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/task.go
// Generate at: 2026-05-15 22:05:18

package repository

import (
	"gorm.io/gorm"

	"github.com/niko-admin/niko-admin/internal/model"
)

// TaskRepository handles database operations for Task model.
type TaskRepository struct {
	db *gorm.DB
}

// NewTaskRepository creates a new TaskRepository.
func NewTaskRepository(db *gorm.DB) *TaskRepository {
	return &TaskRepository{db: db}
}

// FindByID finds a task by its ID.
func (r *TaskRepository) FindByID(id string) (*model.Task, error) {
	var item model.Task
	err := r.db.Where("id = ?", id).First(&item).Error
	return &item, err
}

// Create inserts a new task record.
func (r *TaskRepository) Create(item *model.Task) error {
	return r.db.Create(item).Error
}

// Update saves changes to a task record.
func (r *TaskRepository) Update(item *model.Task) error {
	return r.db.Save(item).Error
}

// Delete removes a task by its ID.
func (r *TaskRepository) Delete(id string) error {
	return r.db.Where("id = ?", id).Delete(&model.Task{}).Error
}

// List returns a paginated list of tasks.
func (r *TaskRepository) List(page, pageSize int) ([]model.Task, int64, error) {
	var items []model.Task
	var total int64

	query := r.db.Model(&model.Task{})
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	offset := (page - 1) * pageSize
	err := query.Offset(offset).Limit(pageSize).Order("created_at DESC").Find(&items).Error
	return items, total, err
}
