// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/task.go
// Generate at: 2026-05-15 22:05:18

package repository

import (
	"context"
	"time"

	"gorm.io/gorm"

	"github.com/niko-admin/niko-admin/internal/dto"
	"github.com/niko-admin/niko-admin/internal/model"
	"github.com/niko-admin/niko-admin/internal/pkg/scopes"
)

// TaskRepository handles database operations for Task model.
type TaskRepository struct {
	db *gorm.DB
}

// NewTaskRepository creates a new TaskRepository.
func NewTaskRepository(db *gorm.DB) *TaskRepository {
	return &TaskRepository{db: db}
}

// FindByID finds a task by its ID.
func (r *TaskRepository) FindByID(ctx context.Context, id string) (*model.Task, error) {
	var item model.Task
	err := r.db.WithContext(ctx).Where("id = ?", id).First(&item).Error
	return &item, err
}

// Create inserts a new task record.
func (r *TaskRepository) Create(ctx context.Context, item *model.Task) error {
	return r.db.WithContext(ctx).Create(item).Error
}

// Update saves changes to a task record.
func (r *TaskRepository) Update(ctx context.Context, item *model.Task) error {
	return r.db.WithContext(ctx).Save(item).Error
}

// Delete removes a task by its ID.
func (r *TaskRepository) Delete(ctx context.Context, id string) error {
	return r.db.WithContext(ctx).Where("id = ?", id).Delete(&model.Task{}).Error
}

// List returns a paginated list of tasks with optional filters.
func (r *TaskRepository) List(ctx context.Context, req dto.TaskListRequest) ([]model.Task, int64, error) {
	var items []model.Task
	var total int64

	query := r.db.WithContext(ctx).Model(&model.Task{}).Scopes(req.FilterScopes()...)
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	err := query.Scopes(
		scopes.Paginate(req.GetPage(), req.GetPageSize()),
		scopes.OrderBy(req.Sort, req.Order, model.Task{}.SortableFields()...),
	).Find(&items).Error
	return items, total, err
}

// UpdateStatus updates the status and optionally the finished_at timestamp of a task.
func (r *TaskRepository) UpdateStatus(ctx context.Context, taskID, status string, finishedAt *time.Time) error {
	return r.db.WithContext(ctx).Model(&model.Task{}).Where("id = ?", taskID).Updates(map[string]interface{}{
		"status":      status,
		"finished_at": finishedAt,
	}).Error
}
