// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/task.go
// Generate at: 2026-05-15 22:05:18

// Package repository 提供数据访问层实现，封装 GORM 数据库操作。
package repository

import (
	"context"
	"time"

	"gorm.io/gorm"

	"github.com/niko-admin/niko-admin/internal/dto"
	"github.com/niko-admin/niko-admin/internal/model"
	"github.com/niko-admin/niko-admin/internal/pkg/scopes"
)

// TaskRepository 处理 Task 异步后台任务模型的数据库读写操作
type TaskRepository struct {
	db *gorm.DB // GORM 数据库连接实例
}

// NewTaskRepository 创建并返回一个新的 TaskRepository 实例
func NewTaskRepository(db *gorm.DB) *TaskRepository {
	return &TaskRepository{db: db}
}

// FindByID 根据主键 ID 查询单个任务详情
func (r *TaskRepository) FindByID(ctx context.Context, id string) (*model.Task, error) {
	var item model.Task
	err := r.db.WithContext(ctx).Where("id = ?", id).First(&item).Error
	return &item, err
}

// Create 插入一条新的后台任务记录
func (r *TaskRepository) Create(ctx context.Context, item *model.Task) error {
	return r.db.WithContext(ctx).Create(item).Error
}

// Update 更新任务的记录字段 (如重试次数、错误日志、执行结果等)
func (r *TaskRepository) Update(ctx context.Context, item *model.Task) error {
	return r.db.WithContext(ctx).Save(item).Error
}

// Delete 根据 ID 删除任务记录
func (r *TaskRepository) Delete(ctx context.Context, id string) error {
	return r.db.WithContext(ctx).Where("id = ?", id).Delete(&model.Task{}).Error
}

// List 分页查询并返回满足筛选条件的异步任务列表
func (r *TaskRepository) List(ctx context.Context, req dto.TaskListRequest) ([]model.Task, int64, error) {
	var items []model.Task
	var total int64

	query := r.db.WithContext(ctx).Model(&model.Task{}).Scopes(req.FilterScopes()...)
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	err := query.Scopes(
		scopes.Paginate(req.GetPage(), req.GetPageSize()),
		scopes.OrderBy(req.Sort, req.Order, model.Task{}.SortableFields()...),
	).Find(&items).Error
	return items, total, err
}

// UpdateStatus 快捷更新任务的状态以及可选的完成时间戳 (FinishedAt)
func (r *TaskRepository) UpdateStatus(ctx context.Context, taskID, status string, finishedAt *time.Time) error {
	return r.db.WithContext(ctx).Model(&model.Task{}).Where("id = ?", taskID).Updates(map[string]interface{}{
		"status":      status,
		"finished_at": finishedAt,
	}).Error
}

