// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/user.go
// Generate at: 2026-05-15 22:05:18

// Package repository 提供数据访问层实现，封装 GORM 数据库操作。
package repository

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	"github.com/niko-admin/niko-admin/internal/dto"
	"github.com/niko-admin/niko-admin/internal/model"
	"github.com/niko-admin/niko-admin/internal/pkg/scopes"
)

// UserRepository 处理 User 用户模型的数据持久化操作
type UserRepository struct {
	db *gorm.DB // GORM 数据库连接实例
}

// NewUserRepository 创建并返回一个新的 UserRepository 实例
func NewUserRepository(db *gorm.DB) *UserRepository {
	return &UserRepository{db: db}
}

// WithTx 返回一个绑定了指定事务的 UserRepository 实例
func (r *UserRepository) WithTx(tx *gorm.DB) *UserRepository {
	return &UserRepository{db: tx}
}

// Transaction 在数据库事务中执行 fn，为 fn 提供绑定了该事务的 UserRepository 实例
func (r *UserRepository) Transaction(ctx context.Context, fn func(txRepo *UserRepository) error) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		return fn(r.WithTx(tx))
	})
}

// FindByID 根据用户 ID 查询用户信息
func (r *UserRepository) FindByID(ctx context.Context, id string) (*model.User, error) {
	var item model.User
	err := r.db.WithContext(ctx).Where("id = ?", id).First(&item).Error
	return &item, err
}

// FindByIDForUpdate 根据用户 ID 查询用户信息并获取行级锁 (SELECT ... FOR UPDATE)，必须在事务中调用
func (r *UserRepository) FindByIDForUpdate(ctx context.Context, id string) (*model.User, error) {
	var item model.User
	err := r.db.WithContext(ctx).Clauses(clause.Locking{Strength: "UPDATE"}).Where("id = ?", id).First(&item).Error
	return &item, err
}

// Create 插入一条新的用户记录
func (r *UserRepository) Create(ctx context.Context, item *model.User) error {
	return r.db.WithContext(ctx).Create(item).Error
}

// Update 保存用户记录的所有修改
func (r *UserRepository) Update(ctx context.Context, item *model.User) error {
	return r.db.WithContext(ctx).Save(item).Error
}

// UpdateWithRoles 在单个事务中更新用户信息并重新分配角色
func (r *UserRepository) UpdateWithRoles(ctx context.Context, user *model.User, roleIDs []string) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Save(user).Error; err != nil {
			return err
		}
		if roleIDs != nil {
			var roles []model.Role
			if err := tx.Where("id IN ?", roleIDs).Find(&roles).Error; err != nil {
				return err
			}
			return tx.Model(user).Association("Roles").Replace(roles)
		}
		return nil
	})
}

// Delete 根据用户 ID 删除用户记录并清理关联的角色绑定关系
func (r *UserRepository) Delete(ctx context.Context, id string) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Where("user_id = ?", id).Delete(&model.UserRole{}).Error; err != nil {
			return err
		}
		if err := tx.Where("id = ?", id).Delete(&model.User{}).Error; err != nil {
			return err
		}
		return nil
	})
}

// List 返回包含分页及可选过滤条件的用户列表和总数
func (r *UserRepository) List(ctx context.Context, req dto.UserListRequest) ([]model.User, int64, error) {
	var items []model.User
	var total int64

	query := r.db.WithContext(ctx).Model(&model.User{}).Scopes(req.FilterScopes()...)
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	err := query.Scopes(
		scopes.Paginate(req.GetPage(), req.GetPageSize()),
		scopes.OrderBy(req.Sort, req.Order, model.User{}.SortableFields()...),
	).Preload("Roles").Find(&items).Error
	return items, total, err
}

// ListForExport 返回符合筛选条件的用户列表，用于导出，限制最大导出数量避免单次请求过大。
func (r *UserRepository) ListForExport(ctx context.Context, req dto.UserListRequest, limit int) ([]model.User, error) {
	var items []model.User
	err := r.db.WithContext(ctx).
		Model(&model.User{}).
		Scopes(req.FilterScopes()...).
		Scopes(scopes.OrderBy(req.Sort, req.Order, model.User{}.SortableFields()...), scopes.OrderByDefault()).
		Limit(limit).
		Preload("Roles").
		Find(&items).Error
	return items, err
}

// FindByUsername 根据用户名查询用户，并预加载其关联的角色信息
func (r *UserRepository) FindByUsername(ctx context.Context, username string) (*model.User, error) {
	var user model.User
	err := r.db.WithContext(ctx).Preload("Roles").Where("username = ?", username).First(&user).Error
	return &user, err
}

// FindByEmail 根据邮箱查询用户
func (r *UserRepository) FindByEmail(ctx context.Context, email string) (*model.User, error) {
	var user model.User
	err := r.db.WithContext(ctx).Where("LOWER(email) = LOWER(?)", email).First(&user).Error
	return &user, err
}

// CountByUsername 统计指定用户名的用户数量，可选排除指定用户 ID
func (r *UserRepository) CountByUsername(ctx context.Context, username string, excludeID string) (int64, error) {
	var count int64
	query := r.db.WithContext(ctx).Model(&model.User{}).Where("username = ?", username)
	if excludeID != "" {
		query = query.Where("id != ?", excludeID)
	}
	err := query.Count(&count).Error
	return count, err
}

// CountByEmail 统计指定邮箱的用户数量，可排除指定 ID。
// 参数:
//
//	ctx - 上下文，用于链路追踪与超时控制
//	email - 目标邮箱地址
//	excludeID - 需要排除的用户 ID（用于更新时排除自身）
//
// 返回值:
//
//	int64 - 匹配的用户数量
//	error - 数据库异常时返回
func (r *UserRepository) CountByEmail(ctx context.Context, email string, excludeID string) (int64, error) {
	if email == "" {
		return 0, nil
	}
	var count int64
	query := r.db.WithContext(ctx).Model(&model.User{}).Where("LOWER(email) = LOWER(?)", email)
	if excludeID != "" {
		query = query.Where("id != ?", excludeID)
	}
	err := query.Count(&count).Error
	return count, err
}

// CreateWithRoles 在单个事务中创建用户并分配角色，若分配失败则回滚用户创建
func (r *UserRepository) CreateWithRoles(ctx context.Context, user *model.User, roleIDs []string) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Create(user).Error; err != nil {
			return err
		}
		if len(roleIDs) > 0 {
			var roles []model.Role
			if err := tx.Where("id IN ?", roleIDs).Find(&roles).Error; err != nil {
				return err
			}
			return tx.Model(user).Association("Roles").Replace(roles)
		}
		return nil
	})
}

// UpdatePassword 仅更新用户的密码字段
func (r *UserRepository) UpdatePassword(ctx context.Context, userID, hashedPassword string) error {
	return r.db.WithContext(ctx).Model(&model.User{}).Where("id = ?", userID).Update("password", hashedPassword).Error
}

// MarkEmailVerified 当邮箱匹配时，将用户的邮箱状态标记为已验证
func (r *UserRepository) MarkEmailVerified(ctx context.Context, userID, email string) error {
	return r.db.WithContext(ctx).Model(&model.User{}).
		Where("id = ? AND LOWER(email) = LOWER(?)", userID, email).
		Update("email_verified", true).Error
}

// UpdateLoginAttempts 更新用户的登录尝试次数计数器
func (r *UserRepository) UpdateLoginAttempts(ctx context.Context, userID string, attempts int) error {
	return r.db.WithContext(ctx).Model(&model.User{}).Where("id = ?", userID).Update("login_attempts", attempts).Error
}

// FindByIDWithRoles 根据用户 ID 查询用户，并预加载其关联的角色信息
func (r *UserRepository) FindByIDWithRoles(ctx context.Context, id string) (*model.User, error) {
	var user model.User
	err := r.db.WithContext(ctx).Preload("Roles").Where("id = ?", id).First(&user).Error
	return &user, err
}

// FindMinRoleLevelByUserID 返回用户关联的所有角色中最小的等级（即最高权限级别），如果用户没有关联任何角色则返回 nil
func (r *UserRepository) FindMinRoleLevelByUserID(ctx context.Context, userID string) (*int, error) {
	var level *int
	err := r.db.WithContext(ctx).
		Table("user_roles").
		Select("MIN(roles.level)").
		Joins("JOIN roles ON roles.id = user_roles.role_id").
		Where("user_roles.user_id = ?", userID).
		Scan(&level).Error
	return level, err
}
