// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/user.go
// Generate at: 2026-05-15 22:05:18

package repository

import (
	"gorm.io/gorm"

	"github.com/niko-admin/niko-admin/internal/model"
)

// UserRepository handles database operations for User model.
type UserRepository struct {
	db *gorm.DB
}

// NewUserRepository creates a new UserRepository.
func NewUserRepository(db *gorm.DB) *UserRepository {
	return &UserRepository{db: db}
}

// FindByID finds a user by its ID.
func (r *UserRepository) FindByID(id string) (*model.User, error) {
	var item model.User
	err := r.db.Where("id = ?", id).First(&item).Error
	return &item, err
}

// Create inserts a new user record.
func (r *UserRepository) Create(item *model.User) error {
	return r.db.Create(item).Error
}

// Update saves changes to a user record.
func (r *UserRepository) Update(item *model.User) error {
	return r.db.Save(item).Error
}

// Delete removes a user by its ID.
func (r *UserRepository) Delete(id string) error {
	return r.db.Where("id = ?", id).Delete(&model.User{}).Error
}

// List returns a paginated list of users.
func (r *UserRepository) List(page, pageSize int) ([]model.User, int64, error) {
	var items []model.User
	var total int64

	query := r.db.Model(&model.User{})
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	offset := (page - 1) * pageSize
	err := query.Offset(offset).Limit(pageSize).Order("created_at DESC").Find(&items).Error
	return items, total, err
}
