// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/audit_log.go
// Generate at: 2026-05-15

// Package model 定义系统数据模型，包含 GORM 结构体和数据库表映射。
package model

import "time"

// AuditLog 记录请求级别的审计事件，用于安全审计
type AuditLog struct {
	ID             string    `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID         *string   `gorm:"type:uuid" json:"user_id"`
	Username       string    `gorm:"type:varchar(64)" json:"username"`
	ActionType     string    `gorm:"type:varchar(128)" json:"action_type"`
	ResourceType   string    `gorm:"type:varchar(64)" json:"resource_type"`
	ResourceID     string    `gorm:"type:varchar(64)" json:"resource_id"`
	RequestPath    string    `gorm:"type:varchar(512)" json:"request_path"`
	RequestMethod  string    `gorm:"type:varchar(10)" json:"request_method"`
	RequestIP      string    `gorm:"type:varchar(45)" json:"request_ip"`
	UserAgent      string    `gorm:"type:varchar(512)" json:"user_agent"`
	RequestBody    string    `gorm:"type:text" json:"request_body"`
	ResponseStatus int       `json:"response_status"`
	DurationMs     int64     `json:"duration_ms"`
	ResultSummary  string    `gorm:"type:varchar(255)" json:"result_summary"`
	CreatedAt      time.Time `json:"created_at"`
}

// SortableFields 返回允许排序的字段列表
func (AuditLog) SortableFields() []string {
	return []string{"created_at", "resource_type"}
}

// TableName 覆盖 AuditLog 的默认表名
func (AuditLog) TableName() string {
	return "audit_logs"
}
