// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/audit_log.go
// Generate at: 2026-05-15

package model

import "time"

// AuditLog records user actions for security auditing.
type AuditLog struct {
	ID             string    `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID         *string   `gorm:"type:uuid" json:"user_id"`
	Username       string    `gorm:"type:varchar(64)" json:"username"`
	Action         string    `gorm:"type:varchar(20);not null" json:"action"`
	ResourceType   string    `gorm:"type:varchar(64)" json:"resource_type"`
	ResourceID     string    `gorm:"type:varchar(64)" json:"resource_id"`
	RequestPath    string    `gorm:"type:varchar(512)" json:"request_path"`
	RequestMethod  string    `gorm:"type:varchar(10)" json:"request_method"`
	RequestIP      string    `gorm:"type:varchar(45)" json:"request_ip"`
	UserAgent      string    `gorm:"type:varchar(512)" json:"user_agent"`
	RequestBody    string    `gorm:"type:text" json:"request_body"`
	ResponseStatus int       `json:"response_status"`
	DurationMs     int64     `json:"duration_ms"`
	CreatedAt      time.Time `json:"created_at"`
}

// TableName overrides the default table name for AuditLog.
func (AuditLog) TableName() string {
	return "audit_logs"
}
