// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/permission.go
// Generate at: 2026-05-15

// Package model 定义系统数据模型，包含 GORM 结构体和数据库表映射。
package model

// Permission 类型常量
const (
	PermTypeMenu   = "menu"
	PermTypeButton = "button"
)

// Permission 表示菜单项或API权限，用于RBAC
type Permission struct {
	BaseModel
	Name      string       `gorm:"type:varchar(64);not null" json:"name"`
	Code      string       `gorm:"type:varchar(128);uniqueIndex;not null" json:"code"`
	Path      string       `gorm:"type:varchar(256)" json:"path"`
	Method    string       `gorm:"type:varchar(10)" json:"method"`
	Type      string       `gorm:"type:varchar(20);not null" json:"type"`
	Icon      string       `gorm:"type:varchar(64)" json:"icon"`
	ParentID  *string      `gorm:"type:uuid" json:"parent_id"`
	SortOrder int          `gorm:"default:0" json:"sort_order"`
	Children  []Permission `gorm:"foreignKey:ParentID" json:"children,omitempty"`
}

// SortableFields 返回允许排序的字段列表
func (Permission) SortableFields() []string {
	return []string{"created_at", "name", "sort_order", "code"}
}
