// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/role.go
// Generate at: 2026-05-15

// Package model 定义系统数据模型，包含 GORM 结构体和数据库表映射。
package model

// Role 表示角色，用于RBAC权限分组
type Role struct {
	BaseModel
	Name        string       `gorm:"type:varchar(64);uniqueIndex;not null" json:"name"`
	Description string       `gorm:"type:varchar(256)" json:"description"`
	SortOrder   int          `gorm:"default:0" json:"sort_order"`
	Status      int          `gorm:"type:smallint;default:1" json:"status"`
	Level       int          `gorm:"default:100" json:"level"`
	Permissions []Permission `gorm:"many2many:role_permissions;" json:"permissions,omitempty"`
}

// SortableFields 返回允许排序的字段列表
func (Role) SortableFields() []string {
	return []string{"created_at", "name", "sort_order"}
}

// RolePermission 是角色与权限多对多关系的关联表
type RolePermission struct {
	RoleID       string `gorm:"type:uuid;primaryKey"`
	PermissionID string `gorm:"type:uuid;primaryKey"`
}
