// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/role.go
// Generate at: 2026-05-15

package model

// Role represents a role that groups permissions for RBAC.
type Role struct {
	BaseModel
	Name        string       `gorm:"type:varchar(64);uniqueIndex;not null" json:"name"`
	Description string       `gorm:"type:varchar(256)" json:"description"`
	SortOrder   int          `gorm:"default:0" json:"sort_order"`
	Status      int          `gorm:"type:smallint;default:1" json:"status"`
	Permissions []Permission `gorm:"many2many:role_permissions;" json:"permissions,omitempty"`
}

// SortableFields returns the fields allowed for sorting.
func (Role) SortableFields() []string {
	return []string{"created_at", "name", "sort_order"}
}

// RolePermission is the join table for Role <-> Permission many-to-many relationship.
type RolePermission struct {
	RoleID       string `gorm:"type:uuid;primaryKey"`
	PermissionID string `gorm:"type:uuid;primaryKey"`
}
