// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/task.go
// Generate at: 2026-05-15

package model

import "time"

// Task represents an asynchronous background task.
type Task struct {
	BaseModel
	TaskID       string     `gorm:"type:varchar(128);uniqueIndex" json:"task_id"`
	Type         string     `gorm:"type:varchar(64);not null" json:"type"`
	Payload      string     `gorm:"type:text" json:"payload"`
	Status       string     `gorm:"type:varchar(20);not null" json:"status"` // pending|running|completed|failed
	RetryCount   int        `json:"retry_count"`
	MaxRetries   int        `json:"max_retries"`
	Result       string     `gorm:"type:text" json:"result"`
	ErrorMessage string     `gorm:"type:text" json:"error_message"`
	FinishedAt   *time.Time `json:"finished_at"`
}

// SortableFields returns the fields allowed for sorting.
func (Task) SortableFields() []string {
	return []string{"created_at", "type", "status"}
}
