// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/file.go
// Generate at: 2026-05-15 22:05:18

package service

// FileService handles business logic for File operations.
//
// For simple CRUD, handlers can directly use the repository.
// Add complex business logic methods as needed.
type FileService struct {
	// Add repository dependencies here
}
