// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/permission.go
// Generate at: 2026-05-15 22:05:18

package service

// PermissionService handles business logic for Permission operations.
//
// For simple CRUD, handlers can directly use the repository.
// Add complex business logic methods as needed.
type PermissionService struct {
	// Add repository dependencies here
}
