// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/role.go
// Generate at: 2026-05-15 22:05:18

package service

// RoleService handles business logic for Role operations.
//
// For simple CRUD, handlers can directly use the repository.
// Add complex business logic methods as needed.
type RoleService struct {
	// Add repository dependencies here
}
