// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/user.go
// Generate at: 2026-05-15 22:05:18

package service

// UserService handles business logic for User operations.
//
// For simple CRUD, handlers can directly use the repository.
// Add complex business logic methods as needed.
type UserService struct {
	// Add repository dependencies here
}
